services:
  gauntlet-app :
    build:
      context: .
      dockerfile: Dockerfile
    image: tomyj/root-you:gauntlet
    container_name: root-you-gauntlet
    init: true
    restart: always
    ports:
      - "5000:5000"
