services:
  database:
    image: tomyj/root-you:database
    build:
      context: .
      dockerfile: Dockerfile
    container_name: root-you-database
    ports:
      - "3306:3306"
    volumes:
          - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
